#pragma once

// DRIVERS PINS
#define STEP1_PIN GPIO_NUM_4
#define DIR1_PIN GPIO_NUM_16
#define STEP2_PIN GPIO_NUM_14
#define DIR2_PIN GPIO_NUM_27 
#define ENABLE_UP_PIN GPIO_NUM_18 
#define ENABLE_FRONT_PIN GPIO_NUM_19 
#define ENABLE_RIGHT_PIN GPIO_NUM_21 
#define ENABLE_DOWN_PIN GPIO_NUM_26 
#define ENABLE_BACK_PIN GPIO_NUM_25 
#define ENABLE_LEFT_PIN GPIO_NUM_33 

// STOP RUNNING BUTTON
#define STOP_PIN GPIO_NUM_32 
#define LED_PIN GPIO_NUM_15